import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNavbar from "@/pages/common/component/TopNavbar";
import LeftNavbar from "@/pages/common/component/LeftNavbar";
import QueryProvider from "./component/query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
  

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)  {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
        <TopNavbar/>
        <main className="flex flex-row h-screen">
        <LeftNavbar/>
        {children}
        </main>
        </QueryProvider>
      </body>
    </html>
  );
}
